### PR TITLE
🔖(fix) bump release to 5.4.1

### PR DESCRIPTION
**Pull request by sampaccoud**
## Fixed

- Update `nextcloud` app scripts path to: `/usr/local/bin`
- Create `.ocdata` file in the `data` directory for the Nextcloud image
- Restore `edxapp` custom theme support (front-end translations in `nginx` collectstatic BC)

### CODE REVIEW

**Review by madmatah — APPROVED** [review]

**Review by jmaupetit — COMMENTED** [review]
I would say that it should be a `5.5.0`, WDYT?

**Comment by sampaccoud** [comment]
@jmaupetit I checked the changelog and I would say it's all fixes...

**Review by jmaupetit — APPROVED** [review]
Ok then.

**Comment by sampaccoud** [comment]
@jmaupetit I moved the item under "Changed" to "Fixed".

**Comment by jmaupetit** [comment]
The git commit title scope should have been `patch` and not `fix`. I should have seen that :sweat_smile:

**Pull request closed without merging**
